[package]
name = "completion"
version = "0.1.0"
autobins = false

authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lsp-server = "0.7.6"
lsp-types = "0.95.0"
serde = { version = "1.0.197", features = ["derive"]}
